update responsive_ttest and tests
naplab/naplib-python pull request #181
Opened 2023-07-09 18:39 UTC by gavinmischler

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.
Fix an issue with the computation of t-test statistics for the responsive t-test whereby inconsistent results would be achieved when performing the test on data where each trial had different scales or average values. This would cause each trial, and each retest, to have highly variable test statistics, so especially when using a specific alternative, like "greater" or "less", it was possible for the test to be significant even if the test statistic (after averaging over all trials and retests) to be the wrong sign which indicated that it couldn't possibly be significant.

#### Any other comments?

2023-07-09 19:07 UTC, menoua requested changes
Is there a reason for this change? I like the previous one better. Best to avoid nesting when possible.

2023-07-10 14:51 UTC, gavinmischler commented
> Is there a reason for this change? I like the existing code better. Best to avoid nesting when possible. EDIT: This is about the last commit.

this line 
```if rereference_grid == 'array':```
was causing a failure for python 3.9+ because if rereference_grid was actually a numpy array, then python 3.9+ actually doesn't even let you compare them, and it throws an error instead of just being False.

I can definitely rewrite it to not be nested though, I'll just add `if isinstance(str) and` in front of each string check

2023-07-10 16:02 UTC, menoua commented
> > Is there a reason for this change? I like the existing code better. Best to avoid nesting when possible. EDIT: This is about the last commit.
> 
> this line `if rereference_grid == 'array':` was causing a failure for python 3.9+ because if rereference_grid was actually a numpy array, then python 3.9+ actually doesn't even let you compare them, and it throws an error instead of just being False.
> 
> I can definitely rewrite it to not be nested though, I'll just add `if isinstance(str) and` in front of each string check like this. Should I change it to this?
> 
> ```python
> if isinstance(rereference_grid, str) and rereference_grid == 'array':
>     if 'labels_data' not in raw_data:
>         raise ValueError('Implicit array-based rereferencing not allowed when electrode labels are not specified')
>     rereference_grid = make_contact_rereference_arr(raw_data['labels_data'])
> elif isinstance(rereference_grid, str) and rereference_grid == 'subject':
>     rereference_grid = np.ones((raw_data['data'].shape[1],) * 2, dtype=int)
> elif isinstance(rereference_grid, str):
>     raise ValueError(f'Unknown string rereference_grid mode: {rereference_grid}')
> ```

I see. Seems to be a disagreement between python and numpy how to handle this equality. I simplified your code a bit.

2023-07-10 16:03 UTC, menoua approved these changes

2023-07-10 20:16 UTC, merged